name: Xcode - Build and Analyze

on:
  workflow_dispatch:                            # Allow manual triggering of the workflow
  #  push:
  #    branches: [ "main" ]                     # Trigger the workflow on pushes to the main branch
  #  pull_request:
  #    branches: [ "main" ]                     # Trigger the workflow on pulles to the main branch
    
jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    # runs-on: macos-latest
    runs-on: macos-15
    steps:

      - name: Select Xcode 16.4
        run: |
          sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
          echo "Current Xcode version:"
          xcodebuild -version

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          # scheme_list=$(xcodebuild -list -json | tr -d "\n")
          # default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          scheme="VisitManaagementApp_iOS"
          default="VisitManaagementApp_iOS"
          echo $default | cat >default
          echo Using scheme: $scheme
          echo Using default scheme: $default

      - name: Check current Xcode version
        run: |
          echo "Current Xcode version:"
          xcodebuild -version
          echo "- - - - - - - - - - - - -"
          echo "Available Xcode versions:"
          ls /Applications/ | grep Xcode

      - name: Install the Apple certificate and provisioning profile
        id: profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Debug - List project contents
        run: |
          echo "=== Project Directory Contents ==="
          ls -la
          echo "=== Xcode Project Contents ==="
          if [ -d "VisitManagementApp.xcodeproj" ]; then
            ls -la VisitManagementApp.xcodeproj/
            echo "=== Project.pbxproj exists? ==="
            ls -la VisitManagementApp.xcodeproj/project.pbxproj
          else
            echo "ERROR: VisitManagementApp.xcodeproj not found!"
          fi
          echo "=== Available Schemes ==="
          xcodebuild -list -project VisitManagementApp.xcodeproj || echo "Failed to list schemes"
          echo "=== Available Simulators ==="
          xcrun simctl list devices available
          echo "=== Installed Certificates ==="
          security find-identity -v -p codesigning
          echo "=== Provisioning Profiles ==="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/ || echo "No provisioning profiles found"

          # Create build directory for reports
          mkdir -p build/reports
      
          # Install CocoaPods if you're using it
          # sudo gem install cocoapods
          # pod install
          
          # Install Swift Package Manager dependencies (if needed)
          # xcodebuild -resolvePackageDependencies

      - name: Build iOS App
        env:
          scheme: ${{ 'VisitManaagementApp_iOS' }}
        run: |
          set -o pipefail

          # echo BLOCKED - until code can be added to update xcodebuild to a newer version
          # if [ $scheme = default ]; then scheme=$(cat default); fi

          echo "=== Build Setup ==="
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          echo "Current Xcode version:"
          xcodebuild -version
          echo Using scheme: $scheme
          echo Using filetype_parameter: $filetype_parameter
          echo Using file_to_build: $file_to_build

          # echo "=== Running Build ==="
          # xcodebuild clean archive \
          # -workspace project.xcworkspace  \
          # -scheme "VisitManaagementApp_iOS" \
          # -configuration Debug \
          # -destination generic/platform=iOS \
          # -archivePath build/project.xcarchive \
          # CODE_SIGN_IDENTITY="Apple Distribution: Daryl Cox (6CVN7U97NK)" \
          # PROVISIONING_PROFILE_SPECIFIER="YourProvisioningProfileName" \
          # DEVELOPMENT_TEAM="6CVN7U97NK"

          echo "=== Running Build ==="
          xcodebuild clean build \
          -project VisitManagementApp.xcodeproj  \
          -scheme "VisitManaagementApp_iOS" \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
          -configuration Debug \
          -verbose \
          CODE_SIGN_IDENTITY="Apple Distribution: Daryl Cox (6CVN7U97NK)" \
          CODE_SIGNING_REQUIRED=YES \
          CODE_SIGN_STYLE="Manual" \
          PROVISIONING_PROFILE_SPECIFIER=${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }} \
          DEVELOPMENT_TEAM="6CVN7U97NK" 2>&1 \
          | tee build_output.log \
          | xcpretty --report html --output build/reports/tests.html || {
            echo "Build failed. Here's the raw xcodebuild output:"
            cat build_output.log
            echo "=== CODE SIGNING DEBUG INFO ==="
            security find-identity -v -p codesigning
            echo "=== PROVISIONING PROFILES ==="
            ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
            echo "=== BUILD FAILED ==="
            exit 1
          }

          echo "=== Build Command Exit Code: $? ==="
          if [ $? -ne 0 ]; then
            echo "=== BUILD FAILED - Full Output Below ==="
            cat build_output.log
            exit 1
          fi

          # echo Running: xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
          # xcodebuild clean build analyze -verbose -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
          # xcodebuild clean build analyze -verbose -scheme "$scheme" -"$filetype_parameter" "$file_to_build" >> $GITHUB_OUTPUT | exit ${PIPESTATUS[0]}
          # xcodebuild clean build -verbose -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | exit ${PIPESTATUS[0]}

          # xcodebuild PROVISIONING_PROFILE=${{ steps.profile.outputs.uuid }} -scheme ${{ env.XCODE_PROJECT }}
          #            clean archive -archivePath "Actions" -configuration Release -arch arm64

          # Works on mini at command line (terminal):
          # xcodebuild clean build analyze -verbose -scheme "VisitManaagementApp_iOS" -"project" "VisitManagementApp.xcodeproj"

      - name: Archive iOS app (Debug)
        if: github.ref == 'refs/heads/main'
        env:
          scheme: ${{ 'VisitManaagementApp_iOS' }}
        run: |
          set -o pipefail

          # Verify code signing setup before archiving
          echo "=== VERIFYING CODE SIGNING SETUP ==="
          security find-identity -v -p codesigning
          echo "=== AVAILABLE PROVISIONING PROFILES ==="
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/

          xcodebuild archive \
            -project VisitManagementApp.xcodeproj \
            -scheme "VisitManaagementApp_iOS" \
            -destination 'generic/platform=iOS' \
            -archivePath build/VisitManagementApp.xcarchive \
            -configuration Debug \
            -verbose \
            CODE_SIGN_IDENTITY="Apple Distribution: Daryl Cox (6CVN7U97NK)" \
            CODE_SIGNING_REQUIRED=YES \
            CODE_SIGN_STYLE="Manual" \
            PROVISIONING_PROFILE_SPECIFIER=${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }} \
            DEVELOPMENT_TEAM="6CVN7U97NK" 2>&1 \
            OTHER_CODE_SIGN_FLAGS="--timestamp" \
            | tee archive_output.log || {
              echo "=== ARCHIVE FAILED - DETAILED DEBUG INFO ==="
              echo "Archive log output:"
              cat archive_output.log
              echo ""
              echo "=== CODE SIGNING IDENTITIES ==="
              security find-identity -v -p codesigning
              echo ""
              echo "=== PROVISIONING PROFILES ==="
              find ~/Library/MobileDevice/Provisioning\ Profiles/ -name "*.mobileprovision" -exec sh -c 'echo "=== {} ==="; security cms -D -i "{}" | plutil -p -' \; 2>/dev/null || echo "Could not read provisioning profiles"
              echo ""
              echo "=== KEYCHAIN LIST ==="
              security list-keychains
              echo ""
              echo "=== ARCHIVE DIRECTORY ==="
              ls -la build/ || echo "Build directory not found"
              echo "=== ARCHIVE FAILED ==="
              exit 1
            }
        
          echo "=== ARCHIVE SUCCESSFUL ==="
          echo "Archive contents:"
          ls -la build/VisitManagementApp.xcarchive/
      
      - name: Archive contents
        run: |
          echo "=== ARCHIVE CONTENTS ==="
          ls -la build/VisitManagementApp.xcarchive/
      
      - name: Export IPA
        if: github.ref == 'refs/heads/main'
        run: |
          echo "=== EXPORT OPTIONS PLIST CONTENT ==="
          cat ExportOptions.plist
        
          # Export the archive
          xcodebuild -exportArchive \
            -archivePath build/VisitManagementApp.xcarchive \
            -exportPath build/ \
            -exportOptionsPlist ExportOptions.plist \
            -verbose \
            -allowProvisioningUpdates \
            | tee export_output.log || {
              echo "=== EXPORT FAILED - DEBUG INFO ==="
              cat export_output.log
              echo ""
              echo "=== EXPORT OPTIONS USED ==="
              cat ExportOptions.plist
              echo ""
              echo "=== ARCHIVE CONTENTS ==="
              find build/VisitManagementApp.xcarchive -type f -name "*.plist" -exec sh -c 'echo "=== {} ==="; cat "{}"' \;
              echo "=== EXPORT FAILED ==="
              exit 1
            }
        
          echo "=== EXPORT SUCCESSFUL ==="
          echo "Generated files:"
          ls -la build/

      - name: build/reports/ contents
        run: |
          echo "=== Build/Reports CONTENTS ==="
          ls -la build/reports/
      
      - name: Upload build logs
        # if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build_output.log
            archive_output.log
            export_output.log
            build/reports/
          retention-days: 30

      - name: Upload IPA
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: VisitManagementApp_iOS
          path: build/*.ipa
          retention-days: 30
