name: Build and Sign iOS App

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: macos-latest  # Use a macOS runner for iOS builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}  # Base64 encoded certificate
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }} # Password for the certificate
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }} # Base64 encoded provisioning profile
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}  # Password for the temporary keychain
        run: |
          # Create a temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain

          # Decode and import the certificate into the keychain
          echo $BUILD_CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign

          # Decode and install the provisioning profile
          echo $BUILD_PROVISION_PROFILE_BASE64 | base64 --decode > profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build and Archive the app
        run: |
          xcodebuild clean archive \
          -workspace YourApp.xcworkspace  \
          -scheme YourScheme \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath build/YourApp.xcarchive \
          CODE_SIGN_IDENTITY="Apple Distribution: Your Developer Name (YourTeamID)" \
          PROVISIONING_PROFILE_SPECIFIER="YourProvisioningProfileName" \
          DEVELOPMENT_TEAM="YourTeamID"

      - name: Export the IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath build/YourApp.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath build/ipa

      - name: Upload the IPA
        uses: actions/upload-artifact@v4
        with:
          name: YourApp-IPA
          path: build/ipa/YourApp.ipa

      - name: Clean up temporary keychain
        run: |
          security delete-keychain build.keychain

